/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 员工账户
 */
export interface AccountEntity { 
    /**
     * 主键
     */
    id?: string;
    /**
     * employid
     */
    sourceId?: string;
    /**
     * 编码
     */
    code?: string;
    /**
     * 用户编号
     */
    customerCode?: string;
    /**
     * 账户名
     */
    account?: string;
    /**
     * 密码
     */
    password?: string;
    /**
     * 密钥
     */
    secretkey?: string;
    /**
     * 是否为bs用户
     */
    isBS?: number;
    /**
     * 是否为app用户
     */
    isApp?: number;
    /**
     * 是否为微信用户
     */
    isWechat?: number;
    /**
     * 账户类型 1-系统初始账户 2-员工账户 3-客户账户 4-供应商账户 5-其他
     */
    accountType?: number;
    /**
     * 账户是否有效
     */
    enabledMark?: number;
    /**
     * 有效期
     */
    expMode?: number;
    /**
     * 账户有效终止日期
     */
    expDate?: Date;
    /**
     * 微信的openId
     */
    openId?: string;
    /**
     * 第三方app编号
     */
    appId?: string;
    /**
     * 用户真实姓名
     */
    name?: string;
    /**
     * 用户头像，考虑数据库存储空间问题，废弃
     */
    headIcon?: string;
    /**
     * 用户头像地址
     */
    headImg?: string;
    /**
     * 最后一次访问时间
     */
    lastVisit?: Date;
    /**
     * 最后一次访问ip
     */
    ipAddress?: string;
    /**
     * 登陆总次数
     */
    logOnCount?: number;
    /**
     * 是否单点登录0-否 1-是
     */
    checkOnLine?: number;
    /**
     * 账户状态 0-离线 1-上线 2-下线
     */
    userOnLine?: number;
    /**
     * 账户创建人
     */
    organizeId?: string;
    /**
     * 创建人ID
     */
    createUserId?: string;
    /**
     * 创建人
     */
    createUserName?: string;
    /**
     * 创建日期
     */
    createDate?: Date;
    /**
     * 描述
     */
    description?: string;
}
