/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HtChargefeeresult } from './htChargefeeresult';
import { HtLeasecontractcharge } from './htLeasecontractcharge';
import { HtLeasecontractchargefee } from './htLeasecontractchargefee';
import { HtLeasecontractchargefeeoffer } from './htLeasecontractchargefeeoffer';
import { HtLeasecontractchargeincre } from './htLeasecontractchargeincre';


/**
 * 费用明细
 */
export interface ChargeDetailDTO {
    /**
     * 合同费用基本条款
     */
    contractCharge?: HtLeasecontractcharge;
    /**
     * 条款
     */
    chargeFeeList?: Array<HtLeasecontractchargefee>;
    /**
     * 递增率
     */
    chargeIncreList?: Array<HtLeasecontractchargeincre>;
    /**
     * 优惠
     */
    chargeFeeOfferList?: Array<HtLeasecontractchargefeeoffer>;
    /**
     * 保证金明细
     */
    depositFeeResultList?: Array<HtChargefeeresult>;
    /**
     * 租金明细
     */
    chargeFeeResultList?: Array<HtChargefeeresult>;
}
