/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChargeFeeResultEntity } from './chargeFeeResultEntity';
import { LeaseContractChargeEntity } from './leaseContractChargeEntity';
import { LeaseContractChargeFeeEntity } from './leaseContractChargeFeeEntity';
import { LeaseContractChargeFeeOfferEntity } from './leaseContractChargeFeeOfferEntity';
import { LeaseContractChargeIncreEntity } from './leaseContractChargeIncreEntity';


/**
 * 费用明细
 */
export interface ChargeDetailDTO {
    /**
     * 合同条款主信息
     */
    contractCharge?: LeaseContractChargeEntity;
    /**
     * 条款
     */
    chargeFeeList?: Array<LeaseContractChargeFeeEntity>;
    /**
     * 递增率
     */
    chargeIncreList?: Array<LeaseContractChargeIncreEntity>;
    /**
     * 优惠
     */
    chargeFeeOfferList?: Array<LeaseContractChargeFeeOfferEntity>;
    /**
     * 租金明细
     */
    chargeFeeResultList?: Array<ChargeFeeResultEntity>;

      /**
     * 保证金明细
     */
    depositFeeResultList?: Array<ChargeFeeResultEntity>;
}
