/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// import { HtLeasecontracthouse } from './htLeasecontracthouse';
// import { HtLeasecontractchargefee } from './htLeasecontractchargefee';
import { TreeEntity, HtLeasecontracthouse, HtLeasecontractchargefee, HtChargefeeresult } from '@/model/models';
/**
 * 费用明细
 */
export interface ChargeFeeDetailDTO {
    /**
     * 条款
     */
    chargeFee: HtLeasecontractchargefee;
    /**
     * 房屋
     */
    rooms: Array<HtLeasecontracthouse>;

    //费项
    feeItems: Array<TreeEntity>;

    //费用明细
    chargeData: Array<HtChargefeeresult>;
}
