/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HtChargefeeresult } from './htChargefeeresult';
import { HtLeasecontractcharge } from './htLeasecontractcharge';
import { HtLeasecontractchargefee } from './htLeasecontractchargefee';
import { HtLeasecontractchargefeeoffer } from './htLeasecontractchargefeeoffer';
import { HtLeasecontractchargeincre } from './htLeasecontractchargeincre';
import { htContractapprovelog } from './htContractapprovelog';

/**
 * 费用明细
 */
export interface ChargeDetailDTO {
    /**
     * 合同费用基本条款
     */
    contractCharge?: HtLeasecontractcharge;
    /**
     * 条款
     */
    // chargeFeeList?: Array<HtLeasecontractchargefee>;


    /**
        * 条款
        */
    chargeFee?: HtLeasecontractchargefee;

    /**
     * 递增率
     */
    // chargeIncreList?: Array<HtLeasecontractchargeincre>;

    chargeIncre?: HtLeasecontractchargeincre;

    /**
     * 优惠
     */
    // chargeFeeOfferList?: Array<HtLeasecontractchargefeeoffer>;

    chargeFeeOffer?: HtLeasecontractchargefeeoffer;

    /**
     * 保证金明细
     */
    depositFeeResultList?: Array<HtChargefeeresult>;
    /**
     * 租金明细
     */
    chargeFeeResultList?: Array<HtChargefeeresult>;

    /**
     * 审批记录
     */
    contractapproveLog?: Array<htContractapprovelog>;

}
