/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 租期费用明细
 */
export interface ChargeFeeResultEntity {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    leaseContractChargeId?: string;
    /**
     * 
     */
    startDate?: Date;
    /**
     * 
     */
    endDate?: Date;
    /**
     * 
     */
    feeItemID?: string;
    /**
     * 
     */
    feeItemName?: string;
    /**
     * 
     */
    payDate?: Date;
    /**
     * 
     */
    price?: number;
    /**
     * 
     */
    priceUnit?: string;
    /**
     * 
     */
    totalPrice?: number;
    /**
     * 
     */
    createDate?: Date;
    /**
     * 
     */
    createUserId?: string;
    /**
     * 
     */
    createUserName?: string;
    /**
     * 
     */
    modifyDate?: Date;
    /**
     * 
     */
    modifyUserId?: string;
    /**
     * 
     */
    modifyUserName?: string;
}
