/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 客户信息表
 */
export interface CustomerInfoEntity { 
    /**
     * 主键
     */
    id?: string;
    /**
     * 用户自定义编码
     */
    code?: string;
    /**
     * 客户类型（1-业主/2-租户）
     */
    type?: string;
    /**
     * 客户类别（1-个人/2-企业）
     */
    flag?: string;
    /**
     * 证件类型（1-身份证 2-护照）
     */
    certificateType?: string;
    /**
     * 证件编号
     */
    certificateNO?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 简称
     */
    shortName?: string;
    /**
     * 国籍
     */
    nation?: string;
    /**
     * 性别
     */
    gender?: number;
    /**
     * 出生年月日
     */
    date?: Date;
    /**
     * 电话号码
     */
    telPhoneNum?: string;
    /**
     * 手机号码
     */
    phoneNum?: string;
    /**
     * 联系地址
     */
    address?: string;
    /**
     * 传真号码
     */
    fax?: string;
    /**
     * 邮件地址
     */
    email?: string;
    /**
     * qq号码
     */
    qq?: string;
    /**
     * 微信好
     */
    weChat?: string;
    /**
     * 紧急联系人
     */
    linkMan?: string;
    /**
     * 紧急联系人电话
     */
    linkPhoneNum?: string;
    /**
     * 法人
     */
    legal?: string;
    /**
     * 营业执照
     */
    licene?: string;
    /**
     * 企业性质
     */
    nature?: string;
    /**
     * 注册资本
     */
    capital?: number;
    /**
     * 原营业场所
     */
    original?: string;
    /**
     * 所属机构id
     */
    organizeId?: string;
    /**
     * 备注
     */
    memo?: string;
    /**
     * 有效标志
     */
    enabledMark?: number;
    /**
     * 登陆账号
     */
    account?: string;
    /**
     * 密码
     */
    password?: string;
    /**
     * 父级Id
     */
    parentId?: string;
    /**
     * 创建时间
     */
    createDate?: Date;
    /**
     * 创建人id
     */
    createUserId?: string;
    /**
     * 创建人姓名
     */
    createUserName?: string;
    /**
     * 修改时间
     */
    modifyDate?: Date;
    /**
     * 修改人Id
     */
    modifyUserId?: string;
    /**
     * 修改人姓名
     */
    modifyUserName?: string;
    /**
     * 发证机关
     */
    issuingOrgan?: string;
    /**
     * 统一社会信用代码
     */
    creditCode?: string;
    /**
     * 税务识别号
     */
    taxCode?: string;
    /**
     * 证件地址
     */
    documentAddress?: string;
    /**
     * 是否列入黑名单
     */
    isBlackName?: boolean;
    /**
     * 开户银行
     */
    accountBank?: string;
    /**
     * 经营业态
     */
    businessFormat?: string;
    /**
     * 品牌名称
     */
    brandName?: string;
    /**
     * 银行账号
     */
    bankAccount?: string;
    /**
     * 招牌名称
     */
    signboardName?: string;
    /**
     * 品牌级别
     */
    brandLevel?: string;
}
