/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface CwFeeitem {
    /**
     * Desc:  Default:0  Nullable:True
     */
    calScaleDispose?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeCode?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    feeNo?: number;
    /**
     * Desc:  Default:b'0'  Nullable:True
     */
    isModifyDate?: boolean;
    /**
     * Desc:  Default:0  Nullable:True
     */
    midResultScale?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    createDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeEngName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    feePrice?: number;
    /**
     * Desc:计费起止日期不允许为空  Default:b'1'  Nullable:True
     */
    isNullDate?: boolean;
    /**
     * Desc:  Default:0  Nullable:True
     */
    midScaleDispose?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeInvoice?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeType?: string;
    /**
     * Desc:含税单价  Default:b'1'  Nullable:True
     */
    isTax?: boolean;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeInvoiceNo?: string;
    /**
     * Desc:减免费项  Default:b'0'  Nullable:True
     */
    isCancel?: boolean;
    /**
     * Desc:不允许临时加费  Default:b'0'  Nullable:True
     */
    isTemp?: boolean;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    currency?: string;
    feeItemId?: string;
    /**
     * Desc:  Default:b'0'  Nullable:True
     */
    isCustomizeDate?: boolean;
    /**
     * Desc:  Default:0  Nullable:True
     */
    lastResultScale?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserName?: string;
    /**
     * Desc:计费周期类型  Default:  Nullable:True
     */
    cycleType?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeKind?: string;
    /**
     * Desc:临时加费不允许修改单价  Default:b'0'  Nullable:True
     */
    isEditTemp?: boolean;
    /**
     * Desc:  Default:0  Nullable:True
     */
    lastScaleDispose?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    sysType?: string;
    /**
     * Desc:计费起始日期  Default:  Nullable:True
     */
    beginDate?: Date;
    /**
     * Desc:计费周期  Default:0  Nullable:True
     */
    cycleValue?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeName?: string;
    /**
     * Desc:是否停用  Default:b'0'  Nullable:True
     */
    isEnable?: boolean;
    /**
     * Desc:关联收费项目  Default:  Nullable:True
     */
    linkFee?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    typeCode?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    calResultScale?: number;
    /**
     * Desc:计费终止日期  Default:  Nullable:True
     */
    endDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    feeNature?: string;
    /**
     * Desc:允许在合同中添加  Default:b'1'  Nullable:True
     */
    isInContract?: boolean;
    /**
     * Desc:  Default:  Nullable:True
     */
    memo?: string;
}
