/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface CwMeterreadBill {
    /**
     * Desc:  Default:  Nullable:False
     */
    billId?: string;
    /**
     * Desc:  Default:b'0'  Nullable:True
     */
    isCalculateFee?: boolean;
    parentId?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    billOrder?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    memo?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    readDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    billPrefix?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    meterCode?: string;
    /**
     * Desc:  Default:0  Nullable:False
     */
    readType?: number;
    /**
     * Desc:  Default:CURRENT_TIMESTAMP  Nullable:False
     */
    createDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    meterReader?: string;
    relationId?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    createUserId?: string;
    /**
     * Desc:  Default:CURRENT_TIMESTAMP  Nullable:False
     */
    modifyDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    verifyDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    modifyUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    verifyMemo?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    batchCode?: string;
    /**
     * Desc:结束抄表日期  Default:  Nullable:True
     */
    endReadDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    verifyPerson?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    billCode?: string;
    /**
     * Desc:  Default:b'0'  Nullable:False
     */
    ifVerify?: boolean;
    organizeId?: string;
}
