/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 费项明细
 */
export interface FeeItemDetailEntity { 
    feeItemID?: string;
    feeFormulaOne?: string;
    feeApportion?: string;
    useFormulaTwo?: number;
    feeFormulaTwo?: string;
    useStepPrice?: boolean;
    stepPriceID?: string;
    delayType?: number;
    delayRate?: number;
    splitFee?: boolean;
    bankTransfer?: boolean;
    accPeriodBase?: number;
    accPeriodBaseNum?: number;
    accPeriodBaseUnit?: number;
    accRightBase?: number;
    accRightBaseNum?: number;
    accRightBaseUnit?: number;
    accBillDateBase?: number;
    accBillDateNum?: number;
    accBillDateUnit?: number;
    accBillDateFixed?: number;
    payDeadlineBase?: number;
    payDeadlineNum?: number;
    payDeadlineUnit?: number;
    payDeadlineFixed?: number;
    lateStartDateBase?: number;
    lateStartDateNum?: number;
    lateStartDateUnit?: number;
    lateStartDateFixed?: number;
    lateDataNotIn?: boolean;
    payedCreateCope?: boolean;
    payFeeItemID?: string;
    copeRate?: number;
    copePersonType?: number;
    /**
     * 指定应付用户姓名
     */
    copeUserName?: string;
    /**
     * 指定应付用户ID
     */
    copeUserID?: string;
    /**
     * 应付期间距收款日多少天
     */
    payDateNum?: number;
    /**
     * 应付期间距收款日单位
     */
    payDateUnit?: number;
    useInOrOut?: boolean;
    inOutDate?: number;
    inMethod?: number;
    inFeeMethod?: number;
    outMethod?: number;
    outFeeMethod?: number;
    memo?: string;
    createDate?: Date;
    createUserId?: string;
    createUserName?: string;
    modifyDate?: Date;
    modifyUserId?: string;
    modifyUserName?: string;
}
