/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// import { CwFeeitem } from './cwFeeitem';
// import { CwFeeitemDetail } from './cwFeeitemDetail';


// /**
//  * 费项信息
//  */
// export interface FeeItemData {
//     /**
//      * 主信息
//      */
//     feeItem?: CwFeeitem;
//     /**
//      * 扩展信息
//      */
//     feeItemDetail?: CwFeeitemDetail;
// }
