/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface GmCustomerinfo {
    /**
     * Desc:  Default:  Nullable:True
     */
    bankAccount?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    code?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    fax?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    linkMan?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    nature?: string;
    // /**
    //  * Desc:  Default:  Nullable:True
    //  */
    // telPhoneNum?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    birthdate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    createDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    flag?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    linkPhoneNum?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    organizeId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    type?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    brandLevel?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserId?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    gender?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    memo?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    original?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    weChat?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    brandName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    id?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    phoneNum?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    businessFormat?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    creditCode?: string;
    /**
     * Desc:  Default:b'0'  Nullable:False
     */
    isBlackName?: boolean;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    qq?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    capital?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    documentAddress?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    issuingOrgan?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    shortName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    accountBank?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    certificateNO?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    email?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    legal?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    name?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    signboardName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    address?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    certificateType?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    enabledMark?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    licene?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    nation?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    taxCode?: string;
}
