/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface GmPstructfile {
    /**
     * Desc:  Default:  Nullable:True
     */
    filePassword?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    uploadUserName?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    fileType?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    fileUrl?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    id?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    organizeId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    otherId?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    category?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    pStructId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    fileName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    uploadDate?: Date;
}
