/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface GmRelationpc {
    /**
     * Desc:  Default:0  Nullable:True
     */
    contractType?: number;
    /**
     * Desc:  Default:1  Nullable:True
     */
    state?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    customerId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    customerType?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    enabledMark?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    endDate?: Date;
    /**
     * Desc:  Default:  Nullable:False
     */
    id?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    beginDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    organizeId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    contractId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    pStructId?: string;
}
