/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface GmVendor {
    /**
     * Desc:  Default:  Nullable:True
     */
    bankCcount?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    fullName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    nature?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    taxAddress?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    businessScope?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    id?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    organizeId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    taxNumber?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    innerPhone?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    outerPhone?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    unit?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    manager?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    parentId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    uscCode?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    managerId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    postalcode?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    creditLevel?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    registeredCapital?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    address?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    email?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    shortName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    bank?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    enCode?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    state?: string;
}
