/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 行政合同信息
 */
export interface htAdmincontract {
  /**
   * 唯一键
   */
  id?: string;
  /**
   * 合同编号
   */
  no?: string;
  /**
   * 租赁数量
   */
  amount?: number;

  /**
   * 违约金
   */
  penaltyAmount?: number;

  /**
  * 签订人代码
  */
  signerId?: string;
  /**
   * 签订人
   */
  signer?: string;
  /**
   * 合同签约日期
   */
  signingDate?: Date;
  /**
   * 合同开始日期
   */
  startDate?: Date;
  /**
   * 合同结束日期
   */
  endDate?: Date;
  /**
 * 跟进人代码
 */
  followerId?: string;
  /**
   * 跟进人
   */
  follower?: string;

  /**
 * 经营主体
 */
  businessEntity?: string;

  /**
* 付款方式
*/
  payType?: string;

  /**
 * 渠道类型
 */
  channelType?: string;

    /**
     * Desc:  违约金起算日期
     */
    penaltyDate?: Date;

    /**
    * 违约金比例
    */
   penaltyRatio?: number;

       /**
     * Desc:  Default:0  Nullable:True
     */
    lastResultScale?: number;

        /**
     * Desc:  Default:0  Nullable:True
     */
    lastScaleDispose?: number;

  // /**
  //  * 单价保留小数点位数
  //  */
  // calcPrecision?: number;
  // /**
  //  * 计算精度的方式  0-精确计算结果保留2位小数  1-每步计算保留2位小数
  //  */
  // calcPrecisionMode?: string;
  /**
   * 租客id
   */
  vendorId?: string;
  /**
   * 租客名称
   */
  vendorName?: string;
  /**
   * 租客联系人
   */
  linkMan?: string;
  /**
   * 租客联系人电话
   */
  linkPhone?: string;
  /**
     * 租客地址
     */
  address?: string;

  // /**
  //  * 滞纳金比例
  //  */
  // lateFee?: number;
  // /**
  //  * 滞纳金比例单位
  //  */
  // lateFeeUnit?: string;
  // /**
  //  * 滞纳金上限
  //  */
  // maxLateFee?: number;
  // /**
  //  * 滞纳金上限单位
  //  */
  // maxLateFeeUnit?: string;
  /**
   * 合同状态
   */
  status?: string;
  /**
  * 机构Id
  */
  organizeId?: string;

  /**
  * Desc:  Default:b'0'  Nullable:True
  */
  isRenewal?: boolean;

  /**
 * 续租前合同Id
 */
  preContractId?: string;

  /**
 * 备注
 */
  memo?: string;

  /**
   * Desc:  Default:  Nullable:True
   */
  createDate?: Date;
  /**
   * Desc:  Default:  Nullable:True
   */
  createUserId?: string;
  /**
   * Desc:  Default:  Nullable:True
   */
  createUserName?: string;
  /**
   * Desc:  Default:  Nullable:True
   */
  modifyDate?: Date;
  /**
   * Desc:  Default:  Nullable:True
   */
  modifyUserId?: string;
  /**
   * Desc:  Default:  Nullable:True
   */
  modifyUserName?: string;
}
