/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 条款房屋
 */
export interface HtLeasecontracthouse {

    /**
  * Desc:  Default:  Nullable:True
  */
    createDate?: Date;
 

    /**
 * Desc:  Default:  Nullable:True
 */
    createUserId?: string;

    /**
 * Desc:  Default:  Nullable:True
 */
    roomId?: string;

    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;

    /**
   * Desc:  Default:  Nullable:False
   */
    id?: string;

    /**
 * Desc:  Default:  Nullable:True
 */
    chargeFeeId?: string;

    /**
     * Desc:  Default:  Nullable:True
     */
    modifyDate?: Date;

    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserId?: string;
    /**
     * Desc:递增类型  Default:  Nullable:True
     */
    allName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserName?: string;

    /**
     * Desc:  Default:  Nullable:True
     */
    area?: number;

    rentPrice?: number;
}
