/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface JcAuthorize {
    /**
     * Desc:  Default:  Nullable:True
     */
    createDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    itemId?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    itemType?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    objectId?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    authorizeId?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    sortCode?: number;
    /**
     * Desc:  Default:0  Nullable:True
     */
    category?: number;
}
