/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface KfPollingarea {
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    pStructId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createUserName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyUserName?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    type?: number;
    /**
     * Desc:  Default:0  Nullable:True
     */
    enableMark?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    name?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    typeName?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    enCode?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    organizeId?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    flagNo?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    otherCode?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    flagWay?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    parentId?: string;
    /**
     * Desc:  Default:0  Nullable:True
     */
    auditMark?: number;
    /**
     * Desc:  Default:  Nullable:True
     */
    memo?: string;
    /**
     * Desc:  Default:  Nullable:False
     */
    id?: string;
    /**
     * Desc:  Default:  Nullable:True
     */
    createDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    modifyDate?: Date;
    /**
     * Desc:  Default:  Nullable:True
     */
    psAllName?: string;
}
