/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 租出合同费用条款物业费优惠
 */
export interface LeaseContractChargeFeeOfferEntity {
    /**
     * 唯一键
     */
    id?: string;
    /**
     * 租出合同费用条款唯一键
     */
    leaseContractChargeId?: string;
   
    /**
     * 优惠类型
     */
    type?: string;
    /**
     * 开始时间
     */
    startDate?: Date;
    /**
     * 结束时间
     */
    endDate?: Date;
    /**
     * 备注
     */
    remark?: string;
    /**
     * 开始期数
     */
    startPeriod?: number;
    /**
     * 期长
     */
    periodLength?: number;
    /**
     * 折扣/减免金额/单价减免
     */
    discount?: number;
    createDate?: Date;
    createUserId?: string;
    createUserName?: string;
    modifyDate?: Date;
    modifyUserId?: string;
    modifyUserName?: string;
}
