/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 租出合同费用条款物业费/租期条款
 */
export interface LeaseContractChargeFeeEntity {
    /**
     * 唯一键
     */
    id?: string;
    /**
     * 租出合同费用条款唯一键
     */
    leaseContractChargeId?: string;
    /**
     * 费项ID
     */
    feeItemID?: string;
    /**
     * 费项名称
     */
    feeItemName?: string;
    /**
     * 开始日期
     */
    startDate?: Date;
    /**
     * 结束日期
     */
    endDate?: Date;
    /**
     * 合同单价
     */
    price?: number; 
    /**
     * 合同单价单位
     */
    priceUnit?: string;
    /**
     * 提前付款时间
     */
    advancePayTime?: number; 
    /**
     * 提前付款时间单位
     */
    advancePayTimeUnit?: string; 
    /**
     * 计费类型
     */
    billType?: string; 
    /**
     * 天单价换算规则
     */
    dayPriceConvertRule?: string;
    /**
     * 年天数
     */
    yearDays?: number;
    /**
     * 付费周期（几月一付）
     */
    payCycle?: number; 
    /**
     * 租期划分方式
     */
    rentalPeriodDivided?: string;
    createDate?: Date;
    createUserId?: string;
    createUserName?: string;
    modifyDate?: Date;
    modifyUserId?: string;
    modifyUserName?: string;
}
