/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 租出合同物业条款递增率
 */
export interface LeaseContractChargeIncreEntity {
    /**
     * 唯一键
     */
    id?: string;
    /**
     * 租出合同物业条款唯一键
     */
    leaseContractChargeId?: string;
    /**
     * 递增时间点
     */
    increDate?: Date;
    /**
     * 单价递增
     */
    increPrice?: number;
    /**
     * 单价递增单位代码
     */
    increPriceUnitId?: string;
    /**
     * 单价递增单位
     */
    increPriceUnit?: string;
    /**
     * 保证金递增
     */
    increDeposit?: number;
   /**
     * 保证金递增单位代码
     */
    increDepositUnitId?: string;
    /**
     * 保证金递增单位
     */
    increDepositUnit?: string;

    createDate?: Date;
    createUserId?: string;
    createUserName?: string;
    modifyDate?: Date;
    modifyUserId?: string;
    modifyUserName?: string;
}
