/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 租出合同房源
 */
export interface LeaseContractHouseDTO {
    /**
     * 唯一键
     */
    id?: string; 
    /**
     * 房屋代码
     */
    roomId?: string;
    /**
     * 房号
     */
    name?: string;
    /**
     * 面积
     */
    area?: number; 
    /**
     * 全称
     */
    allName?: string;
}
