/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 租出合同费用条款
 */
export interface LeaseContractChargeEntity {
    /**
     * 唯一键
     */
    id?: string;
    /**
     * 租出合同唯一键
     */
    leaseContractId?: string;
    /**
     * 保证金关联费项ID
     */
    depositFeeItemID?: number;
    /**
     * 租赁面积
     */
    leaseArea?: number;
    /**
     * 单位保证金金额
     */
    deposit?: number;
    /**
     * 保证金金额单位
     */
    depositUnit?: string;

    /**
        * 开始日期
        */
    startDate?: Date;
    /**
     * 结束日期
     */
    endDate?: Date;
    /**
     * 付款日期
     */
    payDate?: Date; 
    createDate?: Date;
    createUserId?: string;
    createUserName?: string;
    modifyDate?: Date;
    modifyUserId?: string;
    modifyUserName?: string;
}
