/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 费用冲抵主表
 */
export interface OffsetMainEntity {
    /**
     * 
     */
    billID?: string;
    /**
     * 
     */
    organizeID?: string;
    /**
     * 客户ID
     */
    customerID?: string;
    /**
     * 单据日期
     */
    billDate?: Date;
    /**
     * 
     */
    billCode?: string;
    /**
     * 是否审核
     */
    ifVerify?: boolean;
    /**
     * 审核人
     */
    verifyPerson?: string;
    /**
     * 
     */
    verifyDate?: Date;
    /**
     * 
     */
    verifyMemo?: string;
    /**
     * 
     */
    createUserId?: string;
    /**
     * 
     */
    createUserName?: string;
    /**
     * 
     */
    createDate?: Date;
    /**
     * 
     */
    modifyUserId?: string;
    /**
     * 
     */
    modifyUserName?: string;
    /**
     * 
     */
    modifyDate?: Date;
    /**
     * 
     */
    memo?: string;
}
