/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 返回分页数据
 */
export interface PageData { 
    /**
     * 数据
     */
    data?: any;
    /**
     * 总页数
     */
    total?: number;
    /**
     * 页码
     */
    pageIndex?: number;
    /**
     * 每页大小
     */
    pageSize?: number;
}
