/**
 * A6资产管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Pagination { 
    /**
     * 查询条件
     */
    conditionJson?: string;
    /**
     * 页码pageIndex
     */
    page?: number;
    /**
     * 结果
     */
    records?: number;
    /**
     * 页面大小pageSize
     */
    rows?: number;
    /**
     * 排序字段orderField
     */
    sidx?: string;
    /**
     * 升降isAsc
     */
    sord?: string;
    /**
     * 总行数
     */
    readonly total?: number;
}
