/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerInfoEntity } from './customerInfoEntity';
import { PStructEntity } from './pStructEntity';
import { PStructFileEntity } from './pStructFileEntity';
import { ParkingDetailEntity } from './parkingDetailEntity';


/**
 * 车库车位信息
 */
export interface ParkingData { 
    /**
     * 房产主信息
     */
    baseInfo?: PStructEntity;
    /**
     * 车位详情
     */
    parkingDetail?: ParkingDetailEntity;
    /**
     * 附件信息
     */
    fileList?: Array<PStructFileEntity>;
    /**
     * 拥有者
     */
    owner?: CustomerInfoEntity;
    /**
     * 租户
     */
    tenant?: CustomerInfoEntity;
}
