/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 车位详细信息
 */
export interface ParkingDetailEntity { 
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    organizeId?: string;
    /**
     * 
     */
    parkingId?: string;
    /**
     * 业主id
     */
    ownerId?: string;
    /**
     * 是否有效的标志
     */
    state?: number;
    /**
     * 
     */
    parkingType?: string;
    /**
     * 
     */
    parkingNature?: string;
    /**
     * 建筑面积
     */
    area?: number;
    /**
     * 计费面积
     */
    chargingArea?: number;
    /**
     * 
     */
    deliveryDate?: Date;
    /**
     * 租户Id
     */
    customerId?: string;
    /**
     * 
     */
    beginRentDate?: Date;
    /**
     * 
     */
    endRentDate?: Date;
    /**
     * 
     */
    carNo?: string;
    /**
     * 
     */
    cardNo?: string;
    /**
     * 
     */
    vehicleBrand?: string;
    /**
     * 
     */
    color?: string;
    /**
     * 
     */
    memo?: string;
    /**
     * 
     */
    createUserId?: string;
    /**
     * 
     */
    createUserName?: string;
    /**
     * 
     */
    createDate?: Date;
    /**
     * 修改时间
     */
    modifyDate?: Date;
    /**
     * 修改人ID
     */
    modifyUserId?: string;
    /**
     * 修改人名称
     */
    modifyUserName?: string;
}
