/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GmCustomerinfo } from './gmCustomerinfo';
import { GmParkingdetail } from './gmParkingdetail';
import { GmPstructure } from './gmPstructure';


/**
 * 车库车位信息
 */
export interface ParkingData {
    /**
     * 房产主信息
     */
    baseInfo?: GmPstructure;
    /**
     * 车位详情
     */
    parkingDetail?: GmParkingdetail;
    /**
     * 拥有者
     */
    owner?: GmCustomerinfo;
    /**
     * 租户
     */
    tenant?: GmCustomerinfo;
}
