/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PollingAreaEntity { 
    /**
     * 编码
     */
    enCode?: string;
    /**
     * 主键
     */
    pCode?: string;
    /**
     * 名称
     */
    name?: string;
    /**
     * 类别
     */
    type?: number;
    /**
     * 类别名称
     */
    typeName?: string;
    /**
     * 其他编码
     */
    otherCode?: string;
    /**
     * 房产ID
     */
    pStructID?: string;
    /**
     * 父Id
     */
    parentId?: string;
    /**
     * 房产全称
     */
    psAllName?: string;
    /**
     * 标识方式
     */
    flagWay?: number;
    /**
     * 标识编码
     */
    flagNo?: string;
    /**
     * 创建时间
     */
    createDate?: Date;
    createUserId?: string;
    createUserName?: string;
    modifyDate?: Date;
    modifyUserId?: string;
    modifyUserName?: string;
    /**
     * 是否可见标记
     */
    enableMark?: number;
    /**
     * 是否审核1-是 0-否
     */
    auditMark?: number;
    memo?: string;
    organizeId?: string;
}
