/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 楼盘信息表
 */
export interface PropertyEntity {
  /**
   * 主键ID
   */
  id?: string;
  /**
   * 房产Id
   */
  pStructId?: string;
  /**
   * 父级Id
   */
  parentId?: string;
  /**
   * 小区名称
   */
  communityName?: string;
  /**
   * 接盘日期
   */
  date?: Date;
  /**
   * 建筑面积
   */
  area?: number;
  /**
   * 占地面积
   */
  coverArea?: number;
  /**
   * 绿化面积
   */
  greenArea?: number;
  /**
   * 容积率
   */
  volumeRate?: number;
  /**
   * 绿化率
   */
  greenRate?: number;
  province?: string;
  city?: string;
  region?: string;
  township?: string;
  /**
   * 楼盘地址
   */
  address?: string;
  metro?: string;
  cicleLine?: string;
  lat?: number;
  lng?: number;
  propertyType?: string;
  /**
   * 建成年份
   */
  createYear?: string;
  /**
   * 开发商
   */
  developerName?: string;
  /**
   * 物业公司
   */
  propertyCompany?: string;
  /**
   * 物业费标准
   */
  feeItemRule?: string;
  /**
   * 预供应时间
   */
  preSupplyDate?: Date;
  /**
   * 预供应说明
   */
  preSupplyMemo?: string;
  /**
   * 所属组织
   */
  organizeId?: string;
  /**
   * 备注
   */
  memo?: string;
  /**
   * 是否审批
   */
  auditMark?: number;
  /**
   * 审批人名称
   */
  auditUserName?: string;
  /**
   * 审批人Id
   */
  auditUserId?: string;
  /**
   * 是否有效的标志
   */
  enabledMark?: number;
  /**
   * 是否发布
   */
  isPublish?: number;
  /**
   * 历史标记
   */
  hitoryMark?: number;
  createUserId?: string;
  createUserName?: string;
  createDate?: Date;
  /**
   * 修改时间
   */
  modifyDate?: Date;
  /**
   * 修改人ID
   */
  modifyUserId?: string;
  /**
   * 修改人名称
   */
  modifyUserName?: string;
}
