/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 房产结构表
 */
export interface PStructEntity { 
    /**
     * 房产主键
     */
    id?: string;
    /**
     * 组织机构Id
     */
    organizeId?: string;
    /**
     * 房产父id
     */
    parentId?: string;
    /**
     * 房产编码（用户可编辑）
     */
    code?: string;
    /**
     * 房产名称
     */
    name?: string;
    /**
     * 全Code
     */
    allCode?: string;
    /**
     * 全名称
     */
    allName?: string;
    /**
     * 房产类别 1-楼盘 2-楼栋 4-楼层 5-房间 6-公共部位 8-车库，9-车位
     */
    type?: number;
    /**
     * 电话号码
     */
    phoneNum?: string;
    /**
     * 是否空置
     */
    activeMark?: number;
    /**
     * 是否有效1-是 0-否
     */
    enabledMark?: number;
    /**
     * 是否发布
     */
    isPublish?: number;
    /**
     * 主图
     */
    mainPic?: string;
    /**
     * 下级数量
     */
    juniorNum?: number;
    /**
     * 建筑面积
     */
    area?: number;
    /**
     * 占地面积
     */
    coverArea?: number;
    /**
     * 备注
     */
    memo?: string;
}
