/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PStructFileEntity { 
    id?: string;
    category?: number;
    pStructId?: string;
    otherId?: string;
    fileType?: number;
    filePassword?: string;
    fileName?: string;
    fileUrl?: string;
    uploadUserName?: string;
    uploadDate?: Date;
    organizeId?: string;
}
