/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PStructEntity } from './pStructEntity';
import { PStructFileEntity } from './pStructFileEntity';
import { PropertyEntity } from './propertyEntity';


/**
 * 房产信息
 */
export interface PStructsData { 
    /**
     * 房产主信息
     */
    data?: PStructEntity;
    /**
     * 小区扩展信息
     */
    model?: PropertyEntity;
    /**
     * 附件信息
     */
    fileList?: Array<PStructFileEntity>;
}
