/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 费用减免
 */
export interface ReductionMainEntity {
    /**
     * 
     */
    billID?: string;
    /**
     * 
     */
    organizeID?: string;
    /**
     * 
     */
    billCode?: string;
    /**
     * 单据日期
     */
    billDate?: Date;
    /**
     * 折扣，默认1
     */
    rebate?: number;
    /**
     * 固定减免金额
     */
    reductionAmount?: number;
    /**
     * 减免费项id
     */
    reductionFeeItemID?: string;
    /**
     * 是否审核
     */
    ifVerify?: boolean;
    /**
     * 审核人
     */
    verifyPerson?: string;
    /**
     * 
     */
    verifyDate?: Date;
    /**
     * 
     */
    verifyMemo?: string;
    /**
     * 
     */
    createUserId?: string;
    /**
     * 
     */
    createUserName?: string;
    /**
     * 
     */
    createDate?: Date;
    /**
     * 
     */
    modifyUserId?: string;
    /**
     * 
     */
    modifyUserName?: string;
    /**
     * 
     */
    modifyDate?: Date;
    /**
     * 数据状态，0正常-1逻辑删除
     */
    status?: number;
    /**
     * 
     */
    memo?: string;
}
