/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 费用减免明细
 */
export interface ReductionDetailEntity {
    /**
     * 
     */
    id?: number;
    /**
     * 主单ID
     */
    mainID?: string;
    /**
     * 减免明细费用Id
     */
    billID?: string;
    /**
     * 减免金额
     */
    reductionAmount?: number;
    /**
     * 
     */
    createUserId?: string;
    /**
     * 
     */
    createUserName?: string;
    /**
     * 
     */
    createDate?: Date;
    /**
     * 
     */
    modifyUserId?: string;
    /**
     * 
     */
    modifyUserName?: string;
    /**
     * 
     */
    modifyDate?: Date;
    /**
     * 数据状态，0正常-1逻辑删除
     */
    status?: number;
    /**
     * 
     */
    memo?: string;
}
