/**
 * A6物业管理系统接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TreeEntity {
   
  /**
   * key
   */
  key?: string; 
  /**
   * parentId
   */
  parentId?: string;  
  /**
   * 标题
   */
  title?: string; 
  value?: string;
  type?: string;
}
